---
kind: pipeline
type: docker
name: build-cd
steps:
- name: Clone
  image: ubuntu:latest
  commands:
  - apt-get update
  - apt-get -y install git
  - git clone https://github.com/tesseract-ocr/tesseract.git
- name: Build
  image: ubuntu:latest
  commands:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get -y upgrade
  - apt-get -y install automake ca-certificates g++ git libtool libleptonica-dev make pkg-config
  - apt-get -y install --no-install-recommends asciidoc docbook-xsl xsltproc
  - apt-get -y install libicu-dev libpango1.0-dev libcairo2-dev
  - cd tesseract
  - ./autogen.sh
  - ./configure --prefix=$(dirname $(pwd))/tes
  - make
  - make install
  - make training
  - make training-install
  - ls -lR $(dirname $(pwd))/tes

- name: docker
  image: plugins/docker
  settings: 
    repo: registry.digitalocean.com/dergluck/tesseract
    registry: registry.digitalocean.com
    username:
      from_secret: regauth
    password:
      from_secret: regauth
    context: bin/
  tags:
    - latest
  depends_on:
    - Build
