---
kind: pipeline
type: docker
name: build-cd
steps:
- name: Clone
  image: ubuntu:latest
  commands:
  - apt-get update
  - apt-get -y install git
  - git clone https://github.com/tesseract-ocr/tesseract.git
- name: Build
  image: ubuntu:latest
  commands:
  - apt-get update
  - apt-get -y install automake ca-certificates g++ git libtool libleptonica-dev make pkg-config
  - apt-get -y install --no-install-recommends asciidoc docbook-xsl xsltproc
  - apt-get -y install install libpango1.0-dev
  - cd tesseract
  - ./autogen.sh
  - ./configure
  - make